In [1]:
from mysql.connector import connect as con
db = con(
    host = 'localhost',
    user = 'hamed',
    password = 'NewPass123!'
)

if db.is_connected:
    print('Successfully connected to MySQL server')

Successfully connected to MySQL server

In [2]:
cur = db.cursor()

In [3]:
cux = cur.execute
cuxm =cur.executemany

In [4]:
qu_sh_db = """SHOW DATABASES"""
cux(qu_sh_db)
databases = cur.fetchall()
for database in databases:
    print (database[0])

information_schema
mysql
online_shop
performance_schema
sys

In [6]:
db_name ='online_shopping'
qu_cr_db = f"""CREATE DATABASE IF NOT EXISTS {db_name}"""
cux(qu_cr_db)
print (f'A database named {db_name} created successfully')
print ('\n ')
print ('#'*70)
print ('\n ')

cux(qu_sh_db)
databases = cur.fetchall()
for database in databases:
    print (database[0])

A database named online_shopping created successfully


######################################################################


information_schema
mysql
online_shop
online_shopping
performance_schema
sys

In [7]:
cux('USE online_shopping')

# Creating table named Users

In [14]:
db_name ='online_shopping'
table_name  = 'Users'
table_columns = """
        (user_id int primary key auto_increment,
        username varchar(50) not null unique,
        password varchar(50) not null,
        name varchar(100) not null,
        email varchar(100) not null,
        contact_number varchar(30),
        street varchar(255),
        city varchar(100),
        state varchar(100),
        postal_code varchar(20),
        country varchar(100),
        registration_date timestamp default current_timestamp);

"""
qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Users created successfully in online_shopping database


######################################################################


Users


######################################################################


columns in  Users:
('user_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('username', 'varchar(50)', 'NO', 'UNI', None, '')
('password', 'varchar(50)', 'NO', '', None, '')
('name', 'varchar(100)', 'NO', '', None, '')
('email', 'varchar(100)', 'NO', '', None, '')
('contact_number', 'varchar(30)', 'YES', '', None, '')
('street', 'varchar(255)', 'YES', '', None, '')
('city', 'varchar(100)', 'YES', '', None, '')
('state', 'varchar(100)', 'YES', '', None, '')
('postal_code', 'varchar(20)', 'YES', '', None, '')
('country', 'varchar(100)', 'YES', '', None, '')
('registration_date', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')

# Creating table named Managers

In [15]:

table_name  = 'Managers'
table_columns = """
(manager_id int primary key auto_increment,
username varchar(50) not null unique,
password varchar(100)not null,
email varchar(100) not null unique,
registration_date timestamp default current_timestamp);

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Managers created successfully in online_shopping database


######################################################################


Managers
Users


######################################################################


columns in  Managers:
('manager_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('username', 'varchar(50)', 'NO', 'UNI', None, '')
('password', 'varchar(100)', 'NO', '', None, '')
('email', 'varchar(100)', 'NO', 'UNI', None, '')
('registration_date', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')

# Creating table nemed Categories

In [21]:
table_name  = 'Categories'
table_columns = """
(category_id int primary key auto_increment,
name varchar(100) not null unique);

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Categories created successfully in online_shopping database


######################################################################


Categories
Managers
Users


######################################################################


columns in  Categories:
('category_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(100)', 'NO', 'UNI', None, '')

In [23]:
# Creating table nemed Brands

In [22]:

table_name  = 'Brands'
table_columns = """
(brand_id int primary key auto_increment,
name varchar(100) not null unique,
status enum("active", "inactive","old") default "active");

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Brands created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
Users


######################################################################


columns in  Brands:
('brand_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(100)', 'NO', 'UNI', None, '')
('status', "enum('active','inactive','old')", 'YES', '', 'active', '')

# Creating table nemed Brands

In [29]:

table_name  = 'Products'
table_columns = """
(product_id int primary key auto_increment,
name varchar(100) not null,
description text,
price decimal(10,2) not null,
stock int not null,
category_id int,
brand_id int,
create_at timestamp default current_timestamp,
status enum("active","inactive") default "active",
foreign key (category_id) references Categories(category_id),
foreign key (brand_id) references Brands(brand_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Products created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
Products
Users


######################################################################


columns in  Products:
('product_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(100)', 'NO', '', None, '')
('description', 'text', 'YES', '', None, '')
('price', 'decimal(10,2)', 'NO', '', None, '')
('stock', 'int', 'NO', '', None, '')
('category_id', 'int', 'YES', 'MUL', None, '')
('brand_id', 'int', 'YES', 'MUL', None, '')
('create_at', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')
('status', "enum('active','inactive')", 'YES', '', 'active', '')

# Creating table nemed ShippingInfo

In [30]:

table_name  = 'ShippingInfo'
table_columns = """
        (shipping_info_id int primary key auto_increment,
        tracking_number varchar(50),
        carrier varchar(100),
        shipping_date date,
        delivery_date date,
        status enum("pending","shipped","delivered","returned") default "pending");

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named ShippingInfo created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
Products
ShippingInfo
Users


######################################################################


columns in  ShippingInfo:
('shipping_info_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('tracking_number', 'varchar(50)', 'YES', '', None, '')
('carrier', 'varchar(100)', 'YES', '', None, '')
('shipping_date', 'date', 'YES', '', None, '')
('delivery_date', 'date', 'YES', '', None, '')
('status', "enum('pending','shipped','delivered','returned')", 'YES', '', 'pending', '')

# Creating table nemed Orders

In [31]:

table_name  = 'Orders'
table_columns = """
        (order_id int primary key auto_increment,
        user_id int,
        order_date timestamp default current_timestamp,
        status enum("pending","processing","shipped","delivered", "cancelled","returned") not null,
        total_amount decimal(10,2) not null,
        shipping_info_id int,
        foreign key (shipping_info_id) references ShippingInfo(shipping_info_id),
        foreign key (user_id) references Users(user_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Orders created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
Orders
Products
ShippingInfo
Users


######################################################################


columns in  Orders:
('order_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('user_id', 'int', 'YES', 'MUL', None, '')
('order_date', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')
('status', "enum('pending','processing','shipped','delivered','cancelled','returned')", 'NO', '', None, '')
('total_amount', 'decimal(10,2)', 'NO', '', None, '')
('shipping_info_id', 'int', 'YES', 'MUL', None, '')

# Creating table nemed OrderDetails

In [35]:

table_name  = 'OrderDetails'
table_columns = """
        (order_detail_id int primary key auto_increment,
        order_id int,
        product_id int,
        quantity int not null,
        price decimal(10,2) not null,
        foreign key (order_id) references Orders(order_id),
        foreign key (product_id) references Products (product_id));
      
"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named OrderDetails created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
OrderDetails
Orders
Products
ShippingInfo
Users


######################################################################


columns in  OrderDetails:
('order_detail_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('order_id', 'int', 'YES', 'MUL', None, '')
('product_id', 'int', 'YES', 'MUL', None, '')
('quantity', 'int', 'NO', '', None, '')
('price', 'decimal(10,2)', 'NO', '', None, '')

# Creating table nemed ShoppingCart

In [36]:

table_name  = 'ShoppingCart'
table_columns = """
        (cart_id int primary key auto_increment,
        user_id int,
        created_at timestamp default current_timestamp,
        updated_at timestamp default current_timestamp,
        foreign key (user_id) references Users(user_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named ShoppingCart created successfully in online_shopping database


######################################################################


Brands
Categories
Managers
OrderDetails
Orders
Products
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  ShoppingCart:
('cart_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('user_id', 'int', 'YES', 'MUL', None, '')
('created_at', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')
('updated_at', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')

# Creating table nemed CartItems

In [38]:

table_name  = 'CartItems'
table_columns = """
        (cart_item_id int primary key auto_increment,
        cart_id int,
        product_id int, 
        quantity int not null,
        foreign key (cart_id) references ShoppingCart(cart_id),
        foreign key (product_id) references Products(product_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named CartItems created successfully in online_shopping database


######################################################################


Brands
CartItems
Categories
Managers
OrderDetails
Orders
Products
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  CartItems:
('cart_item_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('cart_id', 'int', 'YES', 'MUL', None, '')
('product_id', 'int', 'YES', 'MUL', None, '')
('quantity', 'int', 'NO', '', None, '')

# Creating table nemed PurchaseHistory

In [39]:

table_name  = 'PurchaseHistory'
table_columns = """
        (history_id int primary key auto_increment,
        user_id int,
        order_id int, 
        purchase_date timestamp default current_timestamp,
        foreign key (user_id) references Users(user_id),
        foreign key (order_id) references Orders(order_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named PurchaseHistory created successfully in online_shopping database


######################################################################


Brands
CartItems
Categories
Managers
OrderDetails
Orders
Products
PurchaseHistory
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  PurchaseHistory:
('history_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('user_id', 'int', 'YES', 'MUL', None, '')
('order_id', 'int', 'YES', 'MUL', None, '')
('purchase_date', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')

# Creating table nemed Comments

In [42]:

table_name  = 'Comments'
table_columns = """
        (comment_id int primary key auto_increment,
        user_id int,
        product_id int, 
        comment text not null,        
        comment_date timestamp default current_timestamp,
        status enum("approved","inappropriate"),
        moderated_by int, 
        foreign key (user_id) references Users(user_id),
        foreign key (product_id) references Products(product_id),
        foreign key (moderated_by) references Managers(manager_id));

"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Comments created successfully in online_shopping database


######################################################################


Brands
CartItems
Categories
Comments
Managers
OrderDetails
Orders
Products
PurchaseHistory
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  Comments:
('comment_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('user_id', 'int', 'YES', 'MUL', None, '')
('product_id', 'int', 'YES', 'MUL', None, '')
('comment', 'text', 'NO', '', None, '')
('comment_date', 'timestamp', 'YES', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')
('status', "enum('approved','inappropriate')", 'YES', '', None, '')
('moderated_by', 'int', 'YES', 'MUL', None, '')

# Creating table nemed Discounts

In [43]:

table_name  = 'Discounts'
table_columns = """
        (discount_id int primary key auto_increment,
        name varchar(100) not null,
        description text, 
        discount_percentage decimal(5,2) not null,        
        start_date date,
        end_date date);
"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named Discounts created successfully in online_shopping database


######################################################################


Brands
CartItems
Categories
Comments
Discounts
Managers
OrderDetails
Orders
Products
PurchaseHistory
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  Discounts:
('discount_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(100)', 'NO', '', None, '')
('description', 'text', 'YES', '', None, '')
('discount_percentage', 'decimal(5,2)', 'NO', '', None, '')
('start_date', 'date', 'YES', '', None, '')
('end_date', 'date', 'YES', '', None, '')

# Creating table nemed ProductDiscounts

In [45]:

table_name  = 'ProductDiscounts'
table_columns = """
        (product_discount_id int primary key auto_increment,
        product_id int,
        discount_id int, 
        foreign key (product_id) references Products(product_id),
        foreign key (discount_id) references Discounts(discount_id));
"""


qu_cr_tb = f"""CREATE TABLE IF NOT EXISTS {table_name} {table_columns}"""
cux(qu_cr_tb)
print (f'A table named {table_name} created successfully in {db_name} database ')
print ('\n ')
print ('#'*70)
print ('\n ')

# Show tables in database
qu_sh_tb = """SHOW TABLES"""
cux(qu_sh_tb)
tables = cur.fetchall()
for table in tables:
    print (table[0])

print ('\n ')
print ('#'*70)
print ('\n ')

# Show coulmns of table
print (f'columns in  {table_name}:')
qu_col_tb = f"""DESCRIBE {table_name}"""
cux(qu_col_tb)
columns = cur.fetchall()
for column in columns:
    print (column)

A table named ProductDiscounts created successfully in online_shopping database


######################################################################


Brands
CartItems
Categories
Comments
Discounts
Managers
OrderDetails
Orders
ProductDiscounts
Products
PurchaseHistory
ShippingInfo
ShoppingCart
Users


######################################################################


columns in  ProductDiscounts:
('product_discount_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('product_id', 'int', 'YES', 'MUL', None, '')
('discount_id', 'int', 'YES', 'MUL', None, '')